version: 2.1

jobs:
  build-ppa:
    docker:
      - image: cimg/base:stable-18.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - run: sudo add-apt-repository ppa:named-data/ppa
      - run: sudo apt-get install --no-install-recommends libndn-cxx-dev
      - checkout
      - run: make
      - run: sudo make install
  build-nightly:
    docker:
      - image: cimg/base:stable-20.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - run: |
          echo "deb [trusted=yes] https://nfd-nightly-apt.ndn.today/ubuntu focal main" \
            | sudo tee /etc/apt/sources.list.d/nfd-nightly.list
          sudo apt-get update
      - run: sudo apt-get install --no-install-recommends clang-format-11 libndn-cxx-dev
      - checkout
      - run: |
          make lint
          git diff --exit-code
      - run: make
      - run: sudo make install

workflows:
  build:
    jobs:
      - build-ppa
      - build-nightly
