version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable-18.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - run: |
          sudo add-apt-repository ppa:named-data/ppa-dev
          sudo apt-get install libndn-cxx-dev
      - checkout
      - run: make
      - run: sudo make install
