version: 2.1

commands:
  install_deps:
    steps:
      - run: |
          sudo apt-get install --no-install-recommends $(awk '
            /Build-Depends/ { p=1; next }
            p && $1~":" { p=0 }
            p { gsub(",", "", $1); print $1 }
          ' debian/control)

jobs:
  build-ppa:
    docker:
      - image: cimg/base:stable-18.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - checkout
      - run: sudo add-apt-repository ppa:named-data/ppa
      - install_deps
      - run: make
      - run: sudo make install
  build-nightly:
    docker:
      - image: cimg/base:stable-20.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - checkout
      - run: |
          echo "deb [trusted=yes] https://nfd-nightly-apt.ndn.today/ubuntu focal main" \
            | sudo tee /etc/apt/sources.list.d/nfd-nightly.list
          sudo apt-get update
      - install_deps
      - run: make
      - run: sudo make install
      - run: |
          sudo apt-get install --no-install-recommends clang-format-11
          make lint
          git diff --exit-code

workflows:
  build:
    jobs:
      - build-ppa
      - build-nightly
