version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable-18.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - run: |
          sudo add-apt-repository ppa:named-data/ppa
          sudo apt-get install clang-format-8 libndn-cxx-dev
      - checkout
      - run: |
          make lint
          [[ $(git status --porcelain | tee /dev/stderr | wc -l) -eq 0 ]]
      - run: make
      - run: sudo make install
